packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^6
  "@types/node": ^22.13.14
  "@cloudflare/workers-types": ^4.20251213.0
  hono: ^4.8.2
  "@trpc/server": ^11.16.0
  alchemy: ^0.91.2
  next-themes: ^0.4.6
  "@libsql/client": 0.15.15
  libsql: 0.5.22
  "@trpc/client": ^11.16.0
  "@types/react-dom": ^19.2.3
